# Generated by Django 5.0.3 on 2024-04-07 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_book_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
